Repository HBO-ICT-F1/Smarthome, pull requests merged in 2021-01, with the labels that each got.

#10 Recoded Connection base to work with new Arduino server
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nhlstenden/smarthome/connection/Connection.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/Packet.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/PacketType.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/PairResponse.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/Response.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/packets/PacketLogin.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/packets/PacketRoomData.kt
  app/src/main/java/com/nhlstenden/smarthome/utils/Arduino.kt
  app/src/main/res/xml/network_config.xml
Labels: enhancement

#11 Added custom dialogs and toolbar
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nhlstenden/smarthome/activities/MainActivity.kt
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_arduino_dialog.xml
  app/src/main/res/layout/info_dialog.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#12 Added pair dialog and other improvements
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nhlstenden/smarthome/Smarthome.kt
  app/src/main/java/com/nhlstenden/smarthome/activities/MainActivity.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/Connection.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/DTH.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/PairResponse.kt
  app/src/main/java/com/nhlstenden/smarthome/connection/Response.kt
  app/src/main/java/com/nhlstenden/smarthome/dialog/AddArduinoDialog.kt
  app/src/main/java/com/nhlstenden/smarthome/dialog/InfoDialog.kt
  app/src/main/java/com/nhlstenden/smarthome/utils/Arduino.kt
  app/src/main/java/com/nhlstenden/smarthome/utils/Database.kt
  app/src/main/java/com/nhlstenden/smarthome/utils/Notification.kt
  app/src/main/res/layout/add_arduino_dialog.xml
  app/src/main/res/layout/info_dialog.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#13 Create README.md
  README.md
Labels: documentation, enhancement
